#!/usr/bin/env python3
"""
Historical Data Fetcher for Phoenix AI Trading System

This module automatically fetches historical market data from multiple broker APIs
and stores it in Supabase for AI model training.
"""

import os
import sys
import asyncio
import logging
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Tuple
import pandas as pd
import requests
import supabase
from supabase import create_client, Client
import time

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

class HistoricalDataFetcher:
    """Fetches historical data from multiple brokers and stores in Supabase."""
    
    def __init__(self):
        self.supabase_url = os.getenv('SUPABASE_URL')
        self.supabase_key = os.getenv('SUPABASE_SERVICE_ROLE_KEY')
        
        if not self.supabase_url or not self.supabase_key:
            raise ValueError("SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set")
        
        self.supabase: Client = create_client(self.supabase_url, self.supabase_key)
        
        # API endpoints
        self.binance_base = "https://api.binance.com/api/v3"
        self.oanda_base = "https://api-fxpractice.oanda.com/v3"  # Practice account
        
        # API keys (set in environment)
        self.oanda_api_key = os.getenv('OANDA_API_KEY')
        self.alpaca_api_key = os.getenv('ALPACA_API_KEY')
        self.alpaca_secret_key = os.getenv('ALPACA_SECRET_KEY')
        
    async def create_historical_data_table(self) -> None:
        """Create the historical_data table if it doesn't exist."""
        
        # Check if table exists by trying to query it
        try:
            result = self.supabase.table('historical_data').select('id').limit(1).execute()
            logger.info("historical_data table exists")
            return
        except Exception as e:
            logger.info(f"Creating historical_data table: {e}")
        
        # Create table via SQL
        create_table_sql = """
        CREATE TABLE IF NOT EXISTS historical_data (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            broker VARCHAR(50) NOT NULL,
            market VARCHAR(50) NOT NULL,
            timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
            open_price DECIMAL(15,6) NOT NULL,
            high_price DECIMAL(15,6) NOT NULL,
            low_price DECIMAL(15,6) NOT NULL,
            close_price DECIMAL(15,6) NOT NULL,
            volume BIGINT NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
            UNIQUE(broker, market, timestamp)
        );
        
        CREATE INDEX IF NOT EXISTS idx_historical_data_broker_market ON historical_data(broker, market);
        CREATE INDEX IF NOT EXISTS idx_historical_data_timestamp ON historical_data(timestamp);
        CREATE INDEX IF NOT EXISTS idx_historical_data_market_timestamp ON historical_data(market, timestamp);
        """
        
        try:
            # Execute SQL via Supabase RPC
            result = self.supabase.rpc('exec_sql', {'sql': create_table_sql}).execute()
            logger.info("Created historical_data table successfully")
        except Exception as e:
            logger.error(f"Failed to create table: {e}")
            # Try direct SQL execution
            logger.info("Table creation will be handled by Supabase migration")
    
    async def fetch_binance_klines(self, symbol: str, interval: str = '1m', days: int = 90) -> List[Dict]:
        """Fetch kline data from Binance."""
        
        end_time = int(datetime.now().timestamp() * 1000)
        start_time = end_time - (days * 24 * 60 * 60 * 1000)
        
        url = f"{self.binance_base}/klines"
        params = {
            'symbol': symbol,
            'interval': interval,
            'startTime': start_time,
            'endTime': end_time,
            'limit': 1000  # Max per request
        }
        
        all_data = []
        
        try:
            response = requests.get(url, params=params)
            response.raise_for_status()
            data = response.json()
            
            for kline in data:
                all_data.append({
                    'timestamp': datetime.fromtimestamp(int(kline[0]) / 1000),
                    'open': float(kline[1]),
                    'high': float(kline[2]),
                    'low': float(kline[3]),
                    'close': float(kline[4]),
                    'volume': int(kline[5])
                })
            
            logger.info(f"Fetched {len(all_data)} records from Binance for {symbol}")
            
        except Exception as e:
            logger.error(f"Error fetching from Binance: {e}")
            
        return all_data
    
    async def fetch_oanda_data(self, instrument: str, days: int = 90) -> List[Dict]:
        """Fetch candle data from OANDA."""
        
        if not self.oanda_api_key:
            logger.warning("OANDA API key not set, skipping OANDA fetch")
            return []
        
        end_time = datetime.utcnow()
        start_time = end_time - timedelta(days=days)
        
        headers = {
            'Authorization': f'Bearer {self.oanda_api_key}',
            'Content-Type': 'application/json'
        }
        
        params = {
            'price': 'M',  # Midpoint candles
            'granularity': 'M1',  # 1 minute
            'from': start_time.isoformat() + 'Z',
            'to': end_time.isoformat() + 'Z',
            'count': 5000
        }
        
        try:
            url = f"{self.oanda_base}/instruments/{instrument}/candles"
            response = requests.get(url, headers=headers, params=params)
            response.raise_for_status()
            
            data = response.json()
            all_data = []
            
            if 'candles' in data:
                for candle in data['candles']:
                    if candle['complete']:
                        all_data.append({
                            'timestamp': datetime.fromisoformat(candle['time'].replace('Z', '+00:00')),
                            'open': float(candle['mid']['o']),
                            'high': float(candle['mid']['h']),
                            'low': float(candle['mid']['l']),
                            'close': float(candle['mid']['c']),
                            'volume': int(candle['volume'])
                        })
            
            logger.info(f"Fetched {len(all_data)} records from OANDA for {instrument}")
            
        except Exception as e:
            logger.error(f"Error fetching from OANDA: {e}")
            
        return all_data
    
    async def fetch_alpaca_data(self, symbol: str, days: int = 90) -> List[Dict]:
        """Fetch bar data from Alpaca."""
        
        if not self.alpaca_api_key or not self.alpaca_secret_key:
            logger.warning("Alpaca API keys not set, skipping Alpaca fetch")
            return []
        
        headers = {
            'APCA-API-KEY-ID': self.alpaca_api_key,
            'APCA-API-SECRET-KEY': self.alpaca_secret_key
        }
        
        end_date = datetime.now().date()
        start_date = end_date - timedelta(days=days)
        
        # Alpaca requires date format YYYY-MM-DD
        params = {
            'start': start_date.isoformat(),
            'end': end_date.isoformat(),
            'timeframe': '1Min',
            'limit': 10000
        }
        
        try:
            # Use paper trading endpoint
            url = "https://paper-api.alpaca.markets/v2/stocks/{}/bars".format(symbol)
            response = requests.get(url, headers=headers, params=params)
            response.raise_for_status()
            
            data = response.json()
            all_data = []
            
            if 'bars' in data:
                for bar in data['bars']:
                    all_data.append({
                        'timestamp': datetime.fromisoformat(bar['t'].replace('Z', '+00:00')),
                        'open': float(bar['o']),
                        'high': float(bar['h']),
                        'low': float(bar['l']),
                        'close': float(bar['c']),
                        'volume': int(bar['v'])
                    })
            
            logger.info(f"Fetched {len(all_data)} records from Alpaca for {symbol}")
            
        except Exception as e:
            logger.error(f"Error fetching from Alpaca: {e}")
            
        return all_data
    
    async def store_data_batch(self, data: List[Dict], broker: str, market: str) -> None:
        """Store data in Supabase in batches."""
        
        if not data:
            return
        
        # Convert to Supabase format
        records = []
        for item in data:
            records.append({
                'broker': broker,
                'market': market,
                'timestamp': item['timestamp'].isoformat(),
                'open_price': item['open'],
                'high_price': item['high'],
                'low_price': item['low'],
                'close_price': item['close'],
                'volume': item['volume']
            })
        
        # Upsert in batches of 1000
        batch_size = 1000
        for i in range(0, len(records), batch_size):
            batch = records[i:i + batch_size]
            
            try:
                result = self.supabase.table('historical_data').upsert(
                    batch,
                    on_conflict='broker,market,timestamp'
                ).execute()
                
                logger.info(f"Stored {len(batch)} records for {broker}/{market}")
                
            except Exception as e:
                logger.error(f"Error storing batch: {e}")
                # Try individual records
                for record in batch:
                    try:
                        self.supabase.table('historical_data').upsert(
                            record,
                            on_conflict='broker,market,timestamp'
                        ).execute()
                    except Exception as e2:
                        logger.error(f"Error storing individual record: {e2}")
    
    async def fetch_and_store_broker_data(self, broker: str, markets: List[str], days: int = 90) -> None:
        """Fetch and store data for a specific broker."""
        
        logger.info(f"Starting fetch for {broker} - {len(markets)} markets")
        
        for market in markets:
            try:
                data = []
                
                if broker == 'binance':
                    # Convert market format (e.g., BTC/USD -> BTCUSDT)
                    symbol = market.replace('/', '').replace('USD', 'USDT')
                    data = await self.fetch_binance_klines(symbol, '1m', days)
                    
                elif broker == 'oanda':
                    # Convert market format (e.g., EUR/USD -> EUR_USD)
                    instrument = market.replace('/', '_')
                    data = await self.fetch_oanda_data(instrument, days)
                    
                elif broker == 'alpaca':
                    # Alpaca uses symbol format directly
                    data = await self.fetch_alpaca_data(market, days)
                
                if data:
                    await self.store_data_batch(data, broker, market)
                    logger.info(f"Successfully stored {len(data)} records for {broker}/{market}")
                else:
                    logger.warning(f"No data fetched for {broker}/{market}")
                
                # Rate limiting
                await asyncio.sleep(1)
                
            except Exception as e:
                logger.error(f"Error processing {broker}/{market}: {e}")
    
    async def fetch_and_store_historical_data(self, market: str, broker: str, days: int = 90) -> None:
        """Main function to fetch and store historical data."""
        
        try:
            # Ensure table exists
            await self.create_historical_data_table()
            
            # Fetch and store data
            await self.fetch_and_store_broker_data(broker, [market], days)
            
            logger.info(f"Completed historical data fetch for {broker}/{market}")
            
        except Exception as e:
            logger.error(f"Error in fetch_and_store_historical_data: {e}")
            raise

async def main():
    """Main entry point for CLI usage."""
    
    import argparse
    
    parser = argparse.ArgumentParser(description='Fetch historical data from brokers')
    parser.add_argument('--market', required=True, help='Market symbol (e.g., BTC/USD)')
    parser.add_argument('--broker', required=True, choices=['binance', 'oanda', 'alpaca'], 
                       help='Broker to fetch from')
    parser.add_argument('--days', type=int, default=90, help='Number of days to fetch (default: 90)')
    
    args = parser.parse_args()
    
    fetcher = HistoricalDataFetcher()
    await fetcher.fetch_and_store_historical_data(args.market, args.broker, args.days)

if __name__ == "__main__":
    asyncio.run(main())
